apiVersion: v1
kind: BuildConfig
metadata:
    annotations:
        pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
    creationTimestamp: null
    labels:
        app: anguljar-pipeline
        name: anguljar-pipeline
    name: anguljar-pipeline
spec:
    triggers:
        - github:
              secret: secret123
          type: GitHub
        - generic:
              secret: secret123
          type: Generic
    runPolicy: Serial
    source:
        type: None
    strategy:
        jenkinsPipelineStrategy:
            jenkinsfile: |-
                def imageTag = ""

                pipeline {
                  agent {
                    label 'nodejs12'
                  }

                  stages {
                    stage('Git checkout') {
                      steps {
                        git branch: 'openshift', url: 'https://github.com/maslick/anguljar.git'
                      }
                    }

                    stage('Init') {
                      steps {
                        script {
                          imageTag = "develop-build${env.BUILD_NUMBER}-${new Date().format('dd.MM.yyyy')}"
                        }
                      }
                    }

                    stage('Install deps') {
                      steps {
                        sh "npm install"
                      }
                    }

                    stage('Build') {
                      steps {
                        sh "npm run build"
                      }
                    }

                    stage('Test') {
                      steps {
                        sh "echo Testing"
                      }
                    }

                    stage('Build Docker Image') {
                      steps {
                        sh "echo building docker image"
                        sh "mkdir -p deployments"
                        sh "mkdir -p deployments/nginx-cfg"
                        sh "mkdir -p deployments/nginx-start"

                        sh "cp -r dist/anguljar/* deployments/"
                        sh "cp openshift/nginx.conf deployments/"
                        sh "cp openshift/site.conf deployments/nginx-cfg/default.conf"
                        sh "cp openshift/init.sh deployments/nginx-start"


                        sh "ls -la deployments"
                        script {
                          openshift.withCluster() {
                            openshift.withProject("dev") {
                              openshift.selector("bc", "anguljar").startBuild("--from-dir=deployments/", "--follow=true", "--wait=true")
                            }
                          }
                        }
                      }
                    }

                    stage('Deploy to DEV') {
                      steps {
                        sh "echo Deploying to dev"
                        script {
                          openshift.withCluster() {
                            openshift.withProject("dev") {
                              openshift.selector("dc", "anguljar").rollout().latest();
                            }
                            openshift.tag("dev/anguljar:latest", "dev/anguljar:${imageTag}")
                          }
                        }
                      }
                    }
                  }

                  post {
                    always {
                      emailext(
                        to: 'pavel.masloff@gmail.com',
                        body: '${DEFAULT_CONTENT}<br><div align="center"><img align="center" src="https://avatars3.githubusercontent.com/u/5644706?s=460&v=4"></div>',
                        subject: '${DEFAULT_SUBJECT}'
                      )
                    }
                  }
                }
        type: JenkinsPipeline
status:
    lastVersion: 0
